export const copy = {
  lang: "en" as const,
  nav: { home: "Home", projects: "Projects", about: "About", skills: "Stack", contact: "Contact" },
  available: "Open to new projects",
  role: "Full-stack developer",
  hero: ["Clear ideas.", "Code that works."],
  description: "I'm DAIKO. I build systems, websites and automations that make things simpler.",
  viewProjects: "View projects",
  contactMe: "Let's talk",
  featured: "Selected projects",
  projectsTitle: "From problem to product.",
  allProjects: "All projects",
  selected: "SELECTION / 01 — 04",
  stackLabel: "My toolbox",
  stackTitle: "The right technology.\nFor every idea.",
  stackDescription: "From an interface that feels right to the logic that makes it work. These are the tools I build with.",
  stackCta: "Explore my stack",
  aboutLabel: "A little about me",
  aboutTitle: "Curiosity first.\nCode second.",
  aboutShort: "I like understanding how things work. And, more importantly, finding a better way to do them. To me, development is connecting a good idea with a solution someone actually needs.",
  aboutCta: "Meet the developer",
  cta: ["Have an idea?", "Let's make it happen."],
  ctaDescription: "A system, a website, or that task that should already be automated.",
  footer: "Made with intention. And plenty of coffee.",
  top: "Back to top",
  example: "Example project",
  examplesNotice: "Portfolio concepts: illustrative projects and images. Real code and live demo links are still to be added.",
  projectsIntro: "Systems that organize, experiences that connect, and automations that give time back. A selection of what I can build.",
  all: "All",
  filters: { systems: "Systems", automation: "Automation", websites: "Web" },
  details: "View project",
  problem: "The problem",
  solution: "The solution",
  highlights: "Considered down to the details",
  code: "Source code",
  demo: "Live demo",
  pending: "Link pending",
  nextProject: "Next project",
  backProjects: "Back to projects",
  aboutIntro: "I'm DAIKO, a full-stack developer who likes turning complex problems into simple solutions.",
  bio: ["I enjoy the entire journey of a product: understanding what someone needs, building the interface, designing the logic and organizing the data. I'm not interested in adding technology for its own sake; I'm interested in making the solution make sense.", "My curiosity takes me from web development to systems and automation. I love the moment when something that took hours is solved with a well-designed workflow and a few lines of code.", "Away from the editor, I'm still exploring ideas, learning new tools and looking for other ways of doing things. There's always something to improve."],
  draft: "Draft biography · ready to personalize",
  principlesLabel: "How I work",
  principles: [
    { title: "Understand before building", body: "The best solution starts with good questions, not an open code editor." },
    { title: "Simple, not simplistic", body: "Clear interfaces and maintainable code. The complexity stays behind the scenes." },
    { title: "Automate the repetitive", body: "Time is too valuable to spend on tasks a machine can do." },
  ],
  skillsIntro: "It's not about collecting technologies. It's about knowing how to combine them to build something useful, fast and maintainable.",
  folderHint: "Hover or tap a folder to explore. You can drag the technologies around.",
  groups: {
    frontend: { label: "Frontend", description: "Accessible, fast interfaces with attention to detail." },
    backend: { label: "Backend", description: "Business logic, APIs and systems that do the heavy lifting." },
    databases: { label: "Databases", description: "Well-structured data. Efficient queries. A solid foundation." },
    devops: { label: "DevOps & tools", description: "An organized, reproducible workflow, ready to iterate." },
  },
  technologies: "technologies",
  selectedTech: "Selected technology",
  contactIntro: "Tell me what you have in mind. I like good ideas and challenges that don't have a solution yet.",
  name: "Your name", email: "Your email", message: "Tell me about your project", send: "Send message",
  formNotice: "Sample form · sending is not enabled",
  formResult: "This form doesn't send messages yet. You can find me on GitHub.",
  findMe: "You can also find me here",
  unconfigured: "Not configured yet",
  notFound: "That page doesn't exist yet.",
};

export const projects = [
  { slug: "stockline", name: "Stockline", category: "systems", subtitle: "Inventory management, without the friction.", problem: "When inventory lives in disconnected spreadsheets, it's easy to lose track of stock and make decisions with outdated information.", solution: "A centralized dashboard to manage products, track movements and visualize stock levels in one interface.", highlights: ["Inventory dashboard with filters and search", "Low-stock alerts for products", "Movement history and role-based permissions"] },
  { slug: "flowbot", name: "Flowbot", category: "automation", subtitle: "Less repetition. More time to create.", problem: "Copying data between tools and sending notifications manually takes time away from more important work.", solution: "A workflow system that connects events, conditions and actions to automate internal processes with visibility into every execution.", highlights: ["Workflows connected to external APIs", "Execution logging and monitoring", "Retries and error notifications"] },
  { slug: "turnia", name: "Turnia", category: "systems", subtitle: "A calendar that puts everything in place.", problem: "Managing appointments through messages and calls can lead to double bookings, confusion and a poor experience for everyone.", solution: "A booking platform with clear availability, a weekly calendar and centralized appointment management.", highlights: ["Bookings from any device", "Calendar with time-slot availability", "Client and appointment management dashboard"] },
  { slug: "lumen-studio", name: "Lumen Studio", category: "websites", subtitle: "A website as intentional as the brand.", problem: "A creative studio needs a digital presence that communicates its identity and showcases its work without distracting from the content.", solution: "An editorial site combining expressive typography, subtle motion and clear navigation to turn visits into conversations.", highlights: ["Responsive editorial design", "Careful, accessible animations", "Project pages and contact"] },
];