export const copy = {
  lang: "es" as const,
  nav: { home: "Inicio", projects: "Proyectos", about: "Sobre mí", skills: "Stack", contact: "Contacto" },
  available: "Abierto a nuevos proyectos",
  role: "Full-stack developer",
  hero: ["Ideas claras.", "Código que funciona."],
  description: "Soy DAIKO. Construyo sistemas, páginas web y automatizaciones que hacen las cosas más simples.",
  viewProjects: "Ver proyectos",
  contactMe: "Hablemos",
  featured: "Proyectos seleccionados",
  projectsTitle: "Del problema al producto.",
  allProjects: "Todos los proyectos",
  selected: "SELECCIÓN / 01 — 04",
  stackLabel: "Mi caja de herramientas",
  stackTitle: "La tecnología correcta.\nPara cada idea.",
  stackDescription: "De una interfaz que se siente bien a la lógica que la hace funcionar. Estas son las herramientas con las que construyo.",
  stackCta: "Explorar mi stack",
  aboutLabel: "Un poco de mí",
  aboutTitle: "Curiosidad primero.\nCódigo después.",
  aboutShort: "Me gusta entender cómo funcionan las cosas. Y, sobre todo, encontrar una mejor manera de hacerlas. Para mí, desarrollar es conectar una buena idea con una solución que alguien realmente necesita.",
  aboutCta: "Conoce mi historia",
  cta: ["¿Tienes una idea?", "Hagámosla realidad."],
  ctaDescription: "Un sistema, una web o esa tarea que ya debería estar automatizada.",
  footer: "Hecho con intención. Y mucho café.",
  top: "Volver arriba",
  example: "Proyecto de ejemplo",
  examplesNotice: "Conceptos de portafolio: proyectos e imágenes ilustrativos. Los enlaces reales de código y demo están pendientes.",
  projectsIntro: "Sistemas que ordenan, experiencias que conectan y automatizaciones que liberan tiempo. Una selección de lo que puedo construir.",
  all: "Todos",
  filters: { systems: "Sistemas", automation: "Automatización", websites: "Web" },
  details: "Ver proyecto",
  problem: "El problema",
  solution: "La solución",
  highlights: "Pensado hasta el detalle",
  code: "Código",
  demo: "Demo en vivo",
  pending: "Enlace pendiente",
  nextProject: "Siguiente proyecto",
  backProjects: "Volver a proyectos",
  aboutIntro: "Soy DAIKO, un desarrollador full-stack al que le gusta convertir problemas complejos en soluciones simples.",
  bio: ["Disfruto todo el recorrido de un producto: desde entender qué necesita una persona hasta construir la interfaz, diseñar la lógica y organizar los datos. No me interesa sumar tecnología por sumar; me interesa que la solución tenga sentido.", "Mi curiosidad me lleva del desarrollo web a los sistemas y la automatización. Me entusiasma ese momento en el que algo que tomaba horas se resuelve con un flujo bien pensado y unas cuantas líneas de código.", "Cuando no estoy frente al editor, sigo explorando ideas, aprendiendo nuevas herramientas y buscando otras maneras de hacer las cosas. Siempre hay algo que mejorar."],
  draft: "Biografía de borrador · lista para personalizar",
  principlesLabel: "Mi forma de trabajar",
  principles: [
    { title: "Entender antes de construir", body: "La mejor solución empieza con buenas preguntas, no con el editor abierto." },
    { title: "Simple, no simplista", body: "Interfaces claras y código mantenible. Lo complejo se queda detrás de escena." },
    { title: "Automatizar lo repetitivo", body: "El tiempo es demasiado valioso para gastarlo en tareas que una máquina puede hacer." },
  ],
  skillsIntro: "No se trata de coleccionar tecnologías. Se trata de saber combinarlas para construir algo útil, rápido y mantenible.",
  folderHint: "Pasa el cursor o toca una carpeta para explorar. Puedes arrastrar las tecnologías.",
  groups: {
    frontend: { label: "Frontend", description: "Interfaces accesibles, rápidas y con atención al detalle." },
    backend: { label: "Backend", description: "Lógica de negocio, APIs y sistemas que hacen el trabajo pesado." },
    databases: { label: "Bases de datos", description: "Datos bien estructurados. Consultas eficientes. Una base sólida." },
    devops: { label: "DevOps & herramientas", description: "Un flujo de trabajo organizado, reproducible y listo para iterar." },
  },
  technologies: "tecnologías",
  selectedTech: "Tecnología seleccionada",
  contactIntro: "Cuéntame qué tienes en mente. Me gustan las buenas ideas y los retos que todavía no tienen solución.",
  name: "Tu nombre", email: "Tu email", message: "Cuéntame sobre tu proyecto", send: "Enviar mensaje",
  formNotice: "Formulario de muestra · envío no habilitado",
  formResult: "Este formulario todavía no envía mensajes. Puedes encontrarme en GitHub.",
  findMe: "También me encuentras aquí",
  unconfigured: "Por configurar",
  notFound: "Esa página todavía no existe.",
};

export const projects = [
  { slug: "stockline", name: "Stockline", category: "systems", subtitle: "Control de inventario, sin complicaciones.", problem: "Cuando el inventario vive en hojas de cálculo desconectadas, es fácil perder el control del stock y tomar decisiones con información desactualizada.", solution: "Un panel centralizado para administrar productos, registrar movimientos y visualizar niveles de stock en una sola interfaz.", highlights: ["Panel de inventario con filtros y búsqueda", "Alertas para productos con stock bajo", "Historial de movimientos y permisos por rol"] },
  { slug: "flowbot", name: "Flowbot", category: "automation", subtitle: "Menos tareas repetitivas. Más tiempo para crear.", problem: "Copiar datos entre herramientas y enviar avisos manualmente consume tiempo que podría dedicarse a tareas más importantes.", solution: "Un sistema de flujos que conecta eventos, condiciones y acciones para automatizar procesos internos con visibilidad de cada ejecución.", highlights: ["Flujos conectados a APIs externas", "Registro y seguimiento de ejecuciones", "Reintentos y notificaciones de errores"] },
  { slug: "turnia", name: "Turnia", category: "systems", subtitle: "Una agenda que pone todo en su lugar.", problem: "Gestionar citas por mensajes y llamadas puede causar reservas duplicadas, confusiones y una mala experiencia para todos.", solution: "Una plataforma de reservas con disponibilidad clara, calendario semanal y gestión centralizada de citas.", highlights: ["Reservas desde cualquier dispositivo", "Calendario con disponibilidad por horario", "Panel de gestión de clientes y citas"] },
  { slug: "lumen-studio", name: "Lumen Studio", category: "websites", subtitle: "Una web tan intencional como la marca.", problem: "Un estudio creativo necesita una presencia digital que comunique su identidad y muestre su trabajo sin distraer del contenido.", solution: "Un sitio editorial que combina tipografía expresiva, movimiento sutil y una navegación clara para convertir visitas en conversaciones.", highlights: ["Diseño responsive con enfoque editorial", "Animaciones cuidadas y accesibles", "Páginas de proyectos y contacto"] },
];